# Generated by Django 4.2 on 2025-01-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='quality',
            field=models.CharField(default='Fair', max_length=20),
        ),
    ]
