# Generated by Django 4.2 on 2025-01-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_devicetype_remove_category_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'quality')},
            },
        ),
    ]
