# Generated by Django 4.2 on 2025-01-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_amazing_product_price_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_amazing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_good',
        ),
    ]
